### ISSUE TITLE
Returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Dylan1021** [nick-youngblut/MGSIM#5]
Hi, sorry to bother you again,

I run pacbio simulator successfully but got the following error, it seems something wrong but I can't see the details.
```
(mgsim) [dylan1021@csr38 5_2]$ ./run_mul_simulation.sh 
2024-01-09 15:35:57,694 - Reading genome table: /datahome/comp/ericteam/csyiding/DeepMIC/simulation_5_2/genome_list.tsv
2024-01-09 15:35:57,880 -   Getting genome sizes (no. of threads: 256)
2024-01-09 15:36:23,783 - Reading abundance table: /datahome/comp/ericteam/csyiding/DeepMIC/simulation_5_2/communities/comm_wAbund.txt
2024-01-09 15:36:23,985 - Creating sample-taxon list...
2024-01-09 15:36:24,773 - Simulating PacBio reads...
2024-01-09 15:36:24,883 - Simulating PacBio reads...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/MGSIM/SimReads.py", line 484, in sim_simlord
    raise e
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/MGSIM/SimReads.py", line 480, in sim_simlord
    res = subprocess.run(cmd, check=True, shell=True,
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'simlord --min-readlength 500 --num-reads 3 --read-reference /datahome/comp/ericteam/csyiding/DeepMIC/simulation_5_2/checked_genome/GCF_000014445.1_genomic.fna /datahome/comp/ericteam/csyiding/DeepMIC/long_reads/5_2/temp_reads/1/GCF_000014445.1_genomic/pacbio' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/bin/MGSIM", line 8, in <module>
    sys.exit(main())
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/MGSIM/__main__.py", line 69, in main
    func.opt_parse(args['<args>'])
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/MGSIM/Commands/Reads.py", line 197, in opt_parse
    main(args)
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/MGSIM/Commands/Reads.py", line 172, in main
    SimReads.sim_pacbio(sample_taxon,
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/MGSIM/SimReads.py", line 415, in sim_pacbio
    fq_files = p.map(func, sample_taxon)
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
subprocess.CalledProcessError: Command 'simlord --min-readlength 500 --num-reads 3 --read-reference /datahome/comp/ericteam/csyiding/DeepMIC/simulation_5_2/checked_genome/GCF_000014445.1_genomic.fna /datahome/comp/ericteam/csyiding/DeepMIC/long_reads/5_2/temp_reads/1/GCF_000014445.1_genomic/pacbio' returned non-zero exit status 1.
```
and the command I used is
```
MGSIM reads --sr-seq-depth 0 --pb-seq-depth 1e3 --tmp-dir /datahome/comp/ericteam/csyiding/DeepMIC/long_reads/5_2/temp_reads --rndSeed 8294 -n 256 --gzip /datahome/comp/ericteam/csyiding/DeepMIC/simulation_5_2/genome_list.tsv\
            /datahome/comp/ericteam/csyiding/DeepMIC/simulation_5_2/communities/comm_wAbund.txt\
            /datahome/comp/ericteam/csyiding/DeepMIC/long_reads/5_2/reads
```
Is there any problem in my files? Looking forward to your reply, thanks!

**Comment by nick-youngblut** [comment]
I should provide the subprocess stderr & stdout. You can see the `simlord` error directly just by running the command shown in the error: 

```bash
simlord --min-readlength 500 --num-reads 3 --read-reference /datahome/comp/ericteam/csyiding/DeepMIC/simulation_5_2/checked_genome/GCF_000014445.1_genomic.fna /datahome/comp/ericteam/csyiding/DeepMIC/long_reads/5_2/temp_reads/1/GCF_000014445.1_genomic/pacbio
```

**Comment by Dylan1021** [comment]
Thanks!

I found the code where raises the error and print the information, and it seems the var 'name' is too long for 'a.query_name':

```
(mgsim) [dylan1021@csr38 5_2]$ simlord --min-readlength 500 --num-reads 3 --read-reference /datahome/comp/ericteam/csyiding/DeepMIC/simulation_5_2/checked_genome/GCF_000014445.1_genomic.fna /datahome/comp/ericteam/csyiding/DeepMIC/long_reads/5_2/temp_reads/1/GCF_000014445.1_genomic/pacbio
Time for reading/generating the reference: 0:00:00.004788 h
m0/2589/CCS Read=0;length=2589bp;startpos=1822456;chromosome=NC_008531.1_Leuconostoc_mesenteroides_subsp._mesenteroides_ATCC_8293,_complete_sequence;numberOfErrors=22;totalErrorProb=0.0067;passes=5.204573001083242;passesLeft=5;passesRight=6;cutPosition=2059
257
Traceback (most recent call last):
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/bin/simlord", line 11, in <module>
    sys.exit(main())
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/simlord/simlord.py", line 868, in main
    simulate(args)
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/simlord/simlord.py", line 840, in simulate
    sample_reads(reference=reference, num_reads=num_reads,
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/simlord/simlord.py", line 299, in sample_reads
    write_sam_file(sam_writer, name, read, quality_values.encode(), reversals[i],
  File "/home/comp/dylan1021/anaconda3/envs/mgsim/lib/python3.10/site-packages/simlord/simlord.py", line 521, in write_sam_file
    a.query_name = name
  File "pysam/libcalignedsegment.pyx", line 1168, in pysam.libcalignedsegment.AlignedSegment.query_name.__set__
ValueError: query length out of range 257 > 254
```
Could you please give me some suggestion? Is it ok for the following processing if I set 'name[:254]'

**Comment by nick-youngblut** [comment]
I'm guessing that you input fasta includes >=1 sequence name that is very long. Is that the case?

**Comment by Dylan1021** [comment]
yes, like the file I used above is:
```
>NC_008531.1 Leuconostoc mesenteroides subsp. mesenteroides ATCC 8293, complete sequence
TGCTACTTCTTCTATATTAGAAAAGTCGTCGGTTCAATCCATAATCTTCGTTAAATACTATCAACGTAAGATCGTCATTT
...
```
It seems the info 
```>NC_008531.1 Leuconostoc mesenteroides subsp. mesenteroides ATCC 8293, complete sequence```
is too long

**Comment by Dylan1021** [comment]
I set the 'name' to 'name[:254]' as a cutoff, and no more error output, thanks for your help~
